import { addDays, toISODate, today } from "./dates";
import type { Note, Person, PersonType, Project, Task } from "./types";

const t = today();
const iso = (offset: number, time = "12:00") =>
  `${toISODate(addDays(t, offset))}T${time}:00`;
const day = (offset: number) => toISODate(addDays(t, offset));

export const seedPersonTypes: PersonType[] = [
  {
    id: "pt-kontakt",
    name: "Kontakt",
    color: "#6ea8fe",
    fields: [
      { id: "f-lubi", label: "Lubi", kind: "text" },
      { id: "f-nielubi", label: "Nie lubi", kind: "text" },
    ],
  },
  {
    id: "pt-klient",
    name: "Klient",
    color: "#4fd6c0",
    fields: [
      { id: "f-umowa", label: "Numer umowy", kind: "text" },
      { id: "f-zakres", label: "Zakres prac", kind: "text" },
      { id: "f-lubi2", label: "Lubi", kind: "text" },
    ],
  },
  {
    id: "pt-wspolpracownik",
    name: "Współpracownik",
    color: "#b98be0",
    fields: [
      { id: "f-rola", label: "Rola", kind: "text" },
      { id: "f-stawka", label: "Stawka godzinowa", kind: "number" },
    ],
  },
];

export const seedPeople: Person[] = [
  {
    id: "p-anna",
    name: "Anna Kowalska",
    phone: "+48 601 234 567",
    email: "anna.kowalska@firma.pl",
    typeId: "pt-klient",
    values: {
      "f-umowa": "UM/2026/041",
      "f-zakres": "Onboarding aplikacji mobilnej",
      "f-lubi2": "konkrety i krótkie spotkania",
    },
  },
  {
    id: "p-marek",
    name: "Marek Nowak",
    phone: "+48 512 887 213",
    email: "marek.nowak@gmail.com",
    typeId: "pt-kontakt",
    values: {
      "f-lubi": "wspinaczkę, kawę przelewową",
      "f-nielubi": "spotkań przed 10:00",
    },
  },
  {
    id: "p-kasia",
    name: "Katarzyna Zielińska",
    phone: "+48 728 445 902",
    email: "k.zielinska@studio.design",
    typeId: "pt-wspolpracownik",
    values: {
      "f-rola": "Projektantka UI",
      "f-stawka": "180",
    },
  },
  {
    id: "p-piotr",
    name: "Piotr Wiśniewski",
    phone: "+48 604 118 330",
    email: "piotr@wisniewski.dev",
    typeId: "pt-wspolpracownik",
    values: {
      "f-rola": "Backend developer",
      "f-stawka": "210",
    },
  },
  {
    id: "p-ola",
    name: "Aleksandra Mazur",
    phone: "+48 793 220 415",
    email: "ola.mazur@agencja.pl",
    typeId: "pt-klient",
    values: {
      "f-umowa": "UM/2026/037",
      "f-zakres": "Rebranding identyfikacji",
      "f-lubi2": "moodboardy i szybkie iteracje",
    },
  },
  {
    id: "p-tomek",
    name: "Tomasz Lis",
    phone: "+48 505 662 118",
    email: "tomek.lis@interia.pl",
    typeId: "pt-kontakt",
    values: {
      "f-lubi": "planszówki, dobre IPA",
      "f-nielubi": "rozmów telefonicznych",
    },
  },
];

export const seedProjects: Project[] = [
  {
    id: "prj-onboarding",
    name: "Onboarding v2",
    status: "paused",
    importance: "high",
    tags: ["#klient", "#design"],
    blockedReason:
      "czekamy na akceptację budżetu od klienta (Anna, do 15.07).",
    peopleIds: ["p-anna", "p-kasia", "p-piotr"],
    icon: "clock",
    createdAt: iso(-9),
  },
  {
    id: "prj-crm",
    name: "Migracja CRM",
    status: "active",
    importance: "medium",
    tags: ["#wewnętrzne", "#q3"],
    peopleIds: ["p-piotr", "p-tomek"],
    icon: "star",
    createdAt: iso(-14),
  },
  {
    id: "prj-rebranding",
    name: "Rebranding",
    status: "active",
    importance: "low",
    tags: ["#marketing", "#design"],
    peopleIds: ["p-ola", "p-kasia", "p-marek", "p-tomek"],
    icon: "list",
    createdAt: iso(-21),
  },
];

export const seedNotes: Note[] = [
  {
    id: "n-brief",
    kind: "text",
    title: "Brief po rozmowie z Anną",
    body: "Priorytet: skrócić pierwsze uruchomienie do 3 kroków. Anna chce zobaczyć prototyp ekranu powitalnego przed akceptacją budżetu. Wraca z decyzją do 15.07.",
    mentioned: ["p-anna"],
    projectId: "prj-onboarding",
    createdAt: iso(0, "09:40"),
    updatedAt: iso(0, "09:40"),
  },
  {
    id: "n-voice-standup",
    kind: "voice",
    title: "Głosówka po standupie",
    body: "Notatka głosowa o blokerach w migracji.",
    attachmentLabel: "Nagranie · 1:24",
    mentioned: ["p-piotr"],
    projectId: "prj-crm",
    createdAt: iso(0, "11:05"),
    updatedAt: iso(0, "11:05"),
  },
  {
    id: "n-link-inspo",
    kind: "link",
    title: "Inspiracja na onboarding",
    body: "Świetny pattern progresywnego onboardingu — pokazać Kasi.",
    linkUrl: "https://mobbin.com/flows/onboarding",
    linkDesc: "Mobbin — Onboarding flows",
    mentioned: ["p-kasia"],
    projectId: "prj-onboarding",
    createdAt: iso(-1, "16:20"),
    updatedAt: iso(-1, "16:20"),
  },
  {
    id: "n-photo-tablica",
    kind: "photo",
    title: "Tablica po warsztacie",
    body: "Zdjęcie tablicy z priorytetami rebrandingu.",
    attachmentLabel: "Zdjęcie · tablica.jpg",
    mentioned: ["p-ola", "p-kasia"],
    projectId: "prj-rebranding",
    createdAt: iso(-1, "13:45"),
    updatedAt: iso(-1, "13:45"),
  },
  {
    id: "n-marek-kawa",
    kind: "text",
    title: "Kawa z Markiem",
    body: "Marek poleca kontakt do drukarni na materiały po rebrandingu. Umówić się na wrzesień na wspinaczkę.",
    mentioned: ["p-marek"],
    createdAt: iso(-2, "18:10"),
    updatedAt: iso(-2, "18:10"),
  },
  {
    id: "n-crm-eksport",
    kind: "text",
    title: "Eksport danych ze starego CRM",
    body: "Piotr sprawdził: eksport kontaktów działa, ale historia notatek wymaga skryptu. Tomek ma dostęp do starej bazy.",
    mentioned: ["p-piotr", "p-tomek"],
    projectId: "prj-crm",
    createdAt: iso(-3, "10:30"),
    updatedAt: iso(-3, "10:30"),
  },
  {
    id: "n-link-fonty",
    kind: "link",
    title: "Fonty do nowego brandu",
    body: "Para: Space Grotesk + IBM Plex — sprawdzić licencje.",
    linkUrl: "https://fonts.google.com/specimen/Space+Grotesk",
    linkDesc: "Google Fonts — Space Grotesk",
    mentioned: [],
    projectId: "prj-rebranding",
    createdAt: iso(-4, "15:00"),
    updatedAt: iso(-4, "15:00"),
  },
  {
    id: "n-voice-pomysl",
    kind: "voice",
    title: "Notatka głosowa — pomysł",
    body: "Pomysł na aplikację do nawyków, nagrany w drodze.",
    attachmentLabel: "Nagranie · 0:48",
    mentioned: [],
    createdAt: iso(-1, "08:15"),
    updatedAt: iso(-1, "08:15"),
  },
  {
    id: "n-photo-moodboard",
    kind: "photo",
    title: "Moodboard od Oli",
    body: "Pierwsza wersja moodboardu — ciepłe kolory, dużo bieli.",
    attachmentLabel: "Zdjęcie · moodboard.png",
    mentioned: ["p-ola"],
    projectId: "prj-rebranding",
    createdAt: iso(-5, "12:40"),
    updatedAt: iso(-5, "12:40"),
  },
];

export const seedTasks: Task[] = [
  {
    id: "t-wymagania",
    title: "Zebrać wymagania wejściowe",
    column: "done",
    order: 0,
    projectId: "prj-onboarding",
    personId: "p-anna",
    dueDate: day(-6),
    category: "teal",
  },
  {
    id: "t-audyt",
    title: "Audyt obecnego onboardingu",
    column: "done",
    order: 1,
    projectId: "prj-onboarding",
    dueDate: day(-5),
    category: "teal",
  },
  {
    id: "t-flow",
    title: "Mapa przepływu 3 kroków",
    column: "done",
    order: 2,
    projectId: "prj-onboarding",
    personId: "p-kasia",
    dueDate: day(-3),
    category: "teal",
  },
  {
    id: "t-copy",
    title: "Teksty ekranów powitalnych",
    column: "done",
    order: 3,
    projectId: "prj-onboarding",
    dueDate: day(-2),
    category: "teal",
  },
  {
    id: "t-analityka",
    title: "Zdarzenia analityczne onboardingu",
    column: "done",
    order: 4,
    projectId: "prj-onboarding",
    personId: "p-piotr",
    dueDate: day(-2),
    category: "blue",
  },
  {
    id: "t-prototyp",
    title: "Prototyp ekranu powitalnego",
    column: "doing",
    order: 0,
    projectId: "prj-onboarding",
    personId: "p-kasia",
    dueDate: day(0),
    dueTime: "14:00",
    category: "teal",
  },
  {
    id: "t-testy",
    title: "Testy z 3 użytkownikami",
    column: "todo",
    order: 0,
    projectId: "prj-onboarding",
    dueDate: day(2),
    dueTime: "10:00",
    category: "green",
  },
  {
    id: "t-budzet",
    title: "Follow-up: budżet od Anny",
    column: "todo",
    order: 1,
    projectId: "prj-onboarding",
    personId: "p-anna",
    dueDate: day(4),
    category: "orange",
  },
  {
    id: "t-handoff",
    title: "Handoff prototypu do wyceny",
    column: "todo",
    order: 2,
    projectId: "prj-onboarding",
    dueDate: day(6),
    category: "teal",
  },
  {
    id: "t-eksport",
    title: "Skrypt eksportu historii notatek",
    column: "doing",
    order: 1,
    projectId: "prj-crm",
    personId: "p-piotr",
    dueDate: day(0),
    dueTime: "16:30",
    category: "blue",
  },
  {
    id: "t-mapowanie",
    title: "Mapowanie pól kontaktów",
    column: "done",
    order: 5,
    projectId: "prj-crm",
    dueDate: day(-4),
    category: "blue",
  },
  {
    id: "t-dostepy",
    title: "Dostępy do starej bazy",
    column: "done",
    order: 6,
    projectId: "prj-crm",
    personId: "p-tomek",
    dueDate: day(-7),
    category: "blue",
  },
  {
    id: "t-import-test",
    title: "Testowy import na staging",
    column: "done",
    order: 7,
    projectId: "prj-crm",
    dueDate: day(-1),
    category: "blue",
  },
  {
    id: "t-przelaczenie",
    title: "Przełączenie produkcji na nowy CRM",
    column: "todo",
    order: 3,
    projectId: "prj-crm",
    dueDate: day(7),
    category: "orange",
  },
  {
    id: "t-moodboard",
    title: "Feedback do moodboardu",
    column: "done",
    order: 8,
    projectId: "prj-rebranding",
    personId: "p-ola",
    dueDate: day(-1),
    category: "purple",
  },
  {
    id: "t-logo",
    title: "Szkice logo — 3 kierunki",
    column: "doing",
    order: 2,
    projectId: "prj-rebranding",
    personId: "p-kasia",
    dueDate: day(1),
    dueTime: "12:00",
    category: "purple",
  },
  {
    id: "t-drukarnia",
    title: "Wycena z drukarni od Marka",
    column: "todo",
    order: 4,
    projectId: "prj-rebranding",
    personId: "p-marek",
    dueDate: day(-2),
    category: "purple",
  },
  {
    id: "t-ksiegowa",
    title: "Wysłać faktury do księgowej",
    column: "todo",
    order: 5,
    dueDate: day(0),
    dueTime: "18:00",
    category: "green",
  },
  {
    id: "t-przeglad",
    title: "Tygodniowy przegląd notatek",
    column: "todo",
    order: 6,
    dueDate: day(3),
    category: "teal",
  },
];
